server:
  port: 8084

spring:
  application:
    name: admin-service
  profiles:
    active: dev

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: assign_id
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath*:/mapper/**/*.xml

jwt:
  secret: ${JWT_SECRET:d3v-secret-at-least-256-bits-long-for-hs256-algo!!}
  access-token-ttl: 7200
  refresh-token-ttl: 604800
